<?php

/**
 * @file
 * Tide Webform.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_config_ignore_settings_alter().
 */
function tide_webform_config_ignore_settings_alter(array &$settings) {
  // Ignore the Content Rating webform so that it won't be reverted
  // during config sync.
  $settings[] = 'webform.webform.tide_webform_content_rating';
}

/**
 * Implements hook_form_alter().
 */
function tide_webform_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!empty($form['#webform_id']) && $form['#webform_id'] == 'tide_webform_content_rating') {
    $form['#attached']['library'][] = 'tide_webform/content_rating';
  }
}

/**
 * Implements hook_entity_bundle_create().
 */
function tide_webform_entity_bundle_create($entity_type_id, $bundle) {
  /** @var \Drupal\tide_webform\TideWebformFields $fields_helper */
  $fields_helper = \Drupal::service('tide_webform.fields');

  // Map of which fields should be created for which entity types.
  $map = [
    'node' => [$fields_helper::FIELD_SHOW_CONTENT_RATING],
  ];

  foreach ($map as $entity_type_map => $fields_list) {
    if ($entity_type_id != $entity_type_map) {
      continue;
    }

    foreach ($fields_list as $field_name) {
      try {
        // Create/update form display. View display is not created to avoid
        // unexpected fields appearing in UI.
        $field_config = $fields_helper->provisionField($field_name, $entity_type_id, $bundle);
        \Drupal::messenger()->addMessage(t('Added field %name to the %bundle %entity_type entity and form display.', [
          '%name' => $field_config['field_name'],
          '%entity_type' => $entity_type_id,
          '%bundle' => $bundle,
        ]));
      }
      catch (\Exception $e) {
        \Drupal::messenger()->addMessage(t('Unable to add a field %name to the %bundle %entity_type entity: @message', [
          '%name' => $field_name,
          '%entity_type' => $entity_type_id,
          '%bundle' => $bundle,
          '@message' => $e->getMessage(),
        ]), 'error');
      }
    }
  }

}
