<?php

/**
 * @file
 * Tide Webform.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_config_ignore_settings_alter().
 */
function tide_webform_config_ignore_settings_alter(array &$settings) {
  // Ignore the Content Rating webform so that it won't be reverted
  // during config sync.
  $settings[] = 'webform.webform.tide_webform_content_rating';
}

/**
 * Implements hook_form_alter().
 */
function tide_webform_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!empty($form['#webform_id']) && $form['#webform_id'] == 'tide_webform_content_rating') {
    $form['#attached']['library'][] = 'tide_webform/content_rating';
  }
}
