ARG CLI_IMAGE
FROM ${CLI_IMAGE:-builder} as builder

FROM quay.io/dpc_sdp/nginx

ENV WEBROOT=docroot

COPY .bay/global_redirects.conf /etc/nginx/helpers/global_redirects.conf
RUN fix-permissions /etc/nginx

COPY --from=builder /app /app
