<?php

/**
 * @file
 * Tide Media module functionality.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_view().
 */
function tide_media_views_pre_view(ViewExecutable $view, $display_id, array &$args) {
  if ($view->id() == 'media') {
    // Add License field as a filter to the view.
    $expose_array = [
      'exposed' => TRUE,
      'expose' => [
        'operator_id' => 'field_media_license_value_op',
        'label' => 'License',
        'use_operator' => FALSE,
        'operator' => 'field_media_license_value_op',
        'identifier' => 'field_media_license_value',
        'required' => FALSE,
        'remember' => FALSE,
        'multiple' => FALSE,
      ],
      'group_type' => 'group',
      'operator' => 'or',
      'group' => 1,
      'type' => 'select',
    ];
    $view->addHandler('media_page_list', 'filter', 'media__field_media_license', 'field_media_license_value', $expose_array);
  }
}

/**
 * Implements hook_form_alter().
 */
function tide_media_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Hide the "Embedded with Transcript" view mode from non-audio embed.
  if ($form_id == 'entity_embed_dialog') {
    $entity_browser = $form_state->getValue('entity_browser');
    if (!empty($entity_browser['entities'])) {
      /** @var \Drupal\media\Entity\Media $entity */
      $entity = reset($entity_browser['entities']);
      if ($entity && $entity->bundle() != 'audio') {
        unset($form['attributes']['data-entity-embed-display']['#options']['view_mode:media.embedded_with_transcript']);
      }
    }
  }
}
