<?php

/**
 * @file
 * Tide Media module functionality.
 */

use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_view().
 */
function tide_media_views_pre_view(ViewExecutable $view, $display_id, array &$args) {
  if ($view->id() == 'media') {
    // Add License field as a filter to the view.
    $expose_array = [
      'exposed' => TRUE,
      'expose' => [
        'operator_id' => 'field_media_license_value_op',
        'label' => 'License',
        'use_operator' => FALSE,
        'operator' => 'field_media_license_value_op',
        'identifier' => 'field_media_license_value',
        'required' => FALSE,
        'remember' => FALSE,
        'multiple' => FALSE,
      ],
      'group_type' => 'group',
      'operator' => 'or',
      'group' => 1,
      'type' => 'select',
    ];
    $view->addHandler('media_page_list', 'filter', 'media__field_media_license', 'field_media_license_value', $expose_array);
  }
}
