<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Render\Element;
use Drupal\paragraphs\Entity\ParagraphsType;

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function tide_paragraphs_enhanced_modal_theme_suggestions_paragraphs_add_dialog(array $variables) {
  return ['paragraphs_add_dialog__enhanced'];
}

/**
 * Implements hook_theme().
 */
function tide_paragraphs_enhanced_modal_theme($existing, $type, $theme, $path) {
  return [
    'paragraphs_add_dialog__enhanced' => [
      'template' => 'paragraphs-add-dialog--enhanced',
      'base hook' => 'paragraphs_add_dialog',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @see template_preprocess_paragraphs_add_dialog()
 */
function tide_paragraphs_enhanced_modal_preprocess_paragraphs_add_dialog(&$variables) {
  if (isset($variables['buttons'])) {
    $variables['button_enhancements'] = [];
    $placeholder_icon_path = drupal_get_path('module', 'tide_paragraphs_enhanced_modal') . '/icons/placeholder.svg';
    $placeholder_icon_url = file_create_url($placeholder_icon_path);
    foreach (Element::children($variables['buttons']) as $key) {
      $bundle_machine_name = $variables['buttons'][$key]['#bundle_machine_name'];
      /** @var \Drupal\paragraphs\Entity\ParagraphsType $paragraph_type */
      $paragraph_type = ParagraphsType::load($bundle_machine_name);
      if ($paragraph_type) {
        $variables['button_enhancements'][$key] = [
          'description' => $paragraph_type->getDescription(),
          'icon_url' => $paragraph_type->getIconUrl() ?: $placeholder_icon_url,
          'icon' => $paragraph_type->getIconFile(),
        ];
      }
    }
    $variables['#attached']['library'][] = 'tide_paragraphs_enhanced_modal/paragraphs.enhanced_modal';
  }
}
