<?php

/**
 * @file
 * Contains tide_jira.module.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function tide_jira_node_insert(NodeInterface $node) {
  handle_save($node);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function tide_jira_node_update(NodeInterface $node) {
  handle_save($node);
}

/**
 * Handle the node save operation.
 */
function handle_save(NodeInterface $node) {
  // Never let an error working with JIRA stop content from being saved.
  try {
    $moderation_state = $node->get('moderation_state')->value;
    if (($moderation_state === 'needs_review') || ($moderation_state === 'archive_pending')) {
      \Drupal::service('tide_jira.jira_api')->generateJiraRequest($node);
    }
  }
  catch (Exception $e) {
    \Drupal::messenger()->addError("There was an error reaching JIRA. Please contact support.");
    \Drupal::logger('tide_jira')->error($e);
  }
}
