<?php

/**
 * @file
 * Install file.
 */

use Drupal\user\Entity\Role;

/**
 * Implements hook_uninstall().
 */
function tide_test_uninstall() {
  // Remove permissions on Test content type to Approver and Editor.
  $roles = ['approver', 'editor'];
  $permissions = [
    'create test content',
    'delete any test content',
    'delete own test content',
    'delete test revisions',
    'edit any test content',
    'edit own test content',
    'revert test revisions',
    'view test revisions',
  ];

  foreach ($roles as $role_name) {
    $role = Role::load($role_name);
    if ($role) {
      foreach ($permissions as $permission) {
        $role->revokePermission($permission);
      }
      $role->save();
    }
  }
}
