# @see https://github.com/dpc-sdp/bay/blob/master/bay/images/Dockerfile.nginx
ARG CLI_IMAGE
FROM ${CLI_IMAGE:-cli} as cli

FROM singledigital/bay-nginx:latest

ENV WEBROOT=docroot

COPY .docker/global_redirects.conf /etc/nginx/helpers/global_redirects.conf
RUN fix-permissions /etc/nginx

COPY --from=cli /app /app
