<?php

/**
 * @file
 * Tide Landing Page module functionality.
 */

use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_entity_bundle_create().
 */
function tide_landing_page_entity_bundle_create($entity_type_id, $bundle) {
  // Support the new content type in the Referred Content field
  // of the Card automated paragraphs.
  if ($entity_type_id == 'node') {
    $supported_paragraph_types = [
      'card_navigation_featured_auto',
      'card_navigation_auto',
    ];
    foreach ($supported_paragraph_types as $supported_paragraph_type) {
      $field_config = FieldConfig::loadByName("paragraph", $supported_paragraph_type, "field_paragraph_reference");
      if ($field_config) {
        $handler_settings = $field_config->getSetting('handler_settings');
        $handler_settings['target_bundles'][$bundle] = $bundle;
        $field_config->setSetting('handler_settings', $handler_settings);
        $field_config->save();
      }
    }
  }
}
